name: Build and Deploy Affected Apps
on:
  push:
    branches:
      - main

env:
  BEFORE_SHA: ${{ github.event.before }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2

      - name: Install and Build 🔧
        run: yarn

      - name: Build Affected Apps
        run: yarn run nx affected:build --base=$BEFORE_SHA

      - name: Deploy Affected Apps
        run: yarn run nx affected --target=deploy --base=$BEFORE_SHA
