name: Build and Deploy Affected Apps
on:
  push:
    branches:
      - main

env:
  BEFORE_SHA: ${{ github.event.before }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HASURA_URL: https://idleverse-hasura.fly.dev
      HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Install fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install and Build 🔧
        run: |
          yarn
          git config --global user.email ""
          git config --global user.name "Github Bot"

      - name: Build Affected Apps
        run: yarn run nx affected:build --prod --base=$BEFORE_SHA

      - name: Deploy Affected Apps
        run: yarn run nx affected --target=deploy --base=$BEFORE_SHA
